name: Build and Analyze

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Analyze
    runs-on: self-hosted  # Using self-hosted runner since it's running on your local machine
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for SonarQube analysis relevance

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Build Project
        run: mvn clean install

      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: sqp_f14ea207448c26c9105b8962148f4a92b16563d8  # Provided token
          SONAR_HOST_URL: http://192.168.0.185:9000  # Provided URL for local SonarQube instance
        run: |
          echo "SonarQube Host URL: $SONAR_HOST_URL"  # To verify if the URL is correct
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=github \
          -Dsonar.projectName="GitHub"
